name: Tests Ubuntu

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build model
      run: |
        make
        
    - name: Build PhysiBoSS cell lines project
      run: |
        make
        
    - name: Run PhysiBoSS cell lines project
      run: |
        ./PhysiBoSS_Cell_Lines config/PhysiCell_settings_TLGL.xml