name: Tests MacOSX

on:
  push:
  pull_request:
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run : brew install gcc@11
        
    - name: Build PhysiBoSS cell lines project
      run: |
        make PHYSICELL_CPP=g++-11
        
    - name: Run PhysiBoSS cell lines project
      run: |
        ./PhysiBoSS_Cell_Lines config/PhysiCell_settings_TLGL.xml