name: Tests MacOSX

on:
  push:
    branches: [ main, dev ] 
  pull_request:
    branches: [ main, dev ] 
  workflow_dispatch:
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run : brew install gcc@11
        
    - name: Build PhysiBoSS cell lines project
      run: |
        make PHYSICELL_CPP=g++-11
        
    - name: Run PhysiBoSS cell lines project
      run: |
        ./PhysiBoSS_Cell_Lines Variant\ Model\ Files/base_model_file_multiple_interventions.xml